### ISSUE TITLE
发送文本消息不正常

### ISSUE THREAD

**Issue by super1207** [Threkork/Kovi#4]
我写了这样一段代码：
![image](https://github.com/user-attachments/assets/e8477566-9916-427c-b1d5-c2ac7226bc19)
期望得到：
`[富强,民主,文明,和谐]`
实际效果：
![image](https://github.com/user-attachments/assets/452744a0-d7e8-47db-ae43-3a4842948c8b)

我不清楚是设计上本来就是这样还是这是一个bug

后端用的是llonebot v3.31.10
kovi的版本是0.7.3
rust版本rustc 1.80.0 (051478957 2024-07-21)
windows11 x64

**Comment by Threkork** [comment]
我这一切正常，很有可能是服务端不支持cq，请改用Array消息，还有event.reply可以直接回复字符串

**Comment by Threkork** [comment]
查了一下，llonebot需要单独配置消息为cq码

https://llonebot.github.io/zh-CN/guide/faq
